# Generated by Django 3.2.8 on 2021-10-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
