# Generated by Django 3.2.8 on 2021-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
