# Generated by Django 3.2.8 on 2021-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_image_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
