# Generated by Django 3.2.8 on 2021-10-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211018_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.svg', null=True, upload_to='profile/'),
        ),
    ]
